cmd/es_bootloader: add missing (void *) conversion
Avoid error

    cmd/eswin/es_bootloader.c:309:64: error: passing argument 4 of
    ‘spi_flash_write’ makes pointer from integer without a cast
    [-Wint-conversion]
      309 |               src_addr + i * BOOTCHAIN_PACKAGE_SIZE);
          |                        ^
          |                        |
          |                        long long unsigned int

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>