cmd/es_updater: missing es_bootspi_wp_cfg() definition
Avoid error

    cmd/eswin/es_bootloader.c:292:9: error: implicit declaration of
    function ‘es_bootspi_wp_cfg’ [-Wimplicit-function-declaration]
      292 |         es_bootspi_wp_cfg(0);
          |         ^~~~~~~~~~~~~~~~~

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>