cmd/es_bootloader: add missing include
Avoid an error

    cmd/eswin/es_bootloader.c: In function ‘es_spi_flash_probe’:
    cmd/eswin/es_bootloader.c:195:25: error: implicit declaration of
    function ‘device_remove’; did you mean ‘device_active’?
    [-Wimplicit-function-declaration]
      195 |                         device_remove(new, DM_REMOVE_NORMAL);
          |                         ^~~~~~~~~~~~~
          |                         device_active

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>