riscv: eic7700: add missing #include <efi_loader.h>
Undeclared functions should not be used.

    arch/riscv/cpu/eic7700/dram.c: In function ‘efi_add_known_memory’:
    arch/riscv/cpu/eic7700/dram.c:59:17: error:
    implicit declaration of function ‘efi_add_conventional_memory_map’
    [-Wimplicit-function-declaration]
       59 | efi_add_conventional_memory_map(ram_start, ram_end, ram_top);
          | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>